# Generated by Django 2.2.16 on 2021-09-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20210901_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='planacciones',
            name='estadosistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planesacciones_estadosistema', to='proyectos.EstadoSistemas'),
        ),
    ]
